service: nullbros-server

frameworkVersion: "2"

useDotenv: true
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ${env:AWS_REGION}
  apiGateway:
    shouldStartNameWithService: true

  environment:
    NODE_ENV: ${env:NODE_ENV}  
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    JWT_ENCRYPTION: ${env:JWT_ENCRYPTION}
    JWT_EXPIRATION: ${env:JWT_EXPIRATION}
    ACCESS_KEY_ID: ${env:ACCESS_KEY_ID}
    SECRET_ACCESS_KEY: ${env:SECRET_ACCESS_KEY}

functions:
  app:
    handler: src/serverless.handler
    environment:
      SLS_DEBUG: false
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{any+}
          method: any
